### ISSUE TITLE
Web Development Courses to be Completed

### ISSUE THREAD

**Issue by rays0** [rays0/gittth1#2]
## TODO

*Courses left to be completed*

* [ ] Github Basics Course
* [ ] Github in Worskspaces Workshop
* [ ] Hosting a website with Github Pages Workshop
* [ ] Using Github Pages to host free sites Workshop - Pro
* [ ] Build a blog with Jekyll and github Pages Course
* [ ] Create a Jekyll site on Github Workshop
* [ ] Share projects with Github desktop Workshop
* [ ] DOM Scripting by example Course
* [x] Rest API Basics Course
* [x] Framework Basics Course
* [ ] Beginner SQL Track

:tada: 👌 :ok_man: :confetti_ball:
